# Generated by Django 5.0.6 on 2024-08-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
