# Generated by Django 5.0.6 on 2024-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0002_alter_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, help_text='True if accepted, False otherwise'),
        ),
    ]
