# Generated by Django 5.0.6 on 2024-08-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0003_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
