# Generated by Django 5.0.6 on 2024-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0005_order_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(blank=True, help_text='True if accepted, False otherwise', null=True),
        ),
    ]
