# Generated by Django 5.0.6 on 2024-08-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(blank=True, default=None, help_text='True if accepted, False otherwise', null=True),
        ),
    ]
