# Generated by Django 5.0.6 on 2024-08-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='menu_images/default.jpg', upload_to='menu_images/'),
        ),
    ]
