# Generated by Django 5.0.6 on 2024-08-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0008_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='../menu_images/20240308_122033.jpg', upload_to='menu_images/'),
        ),
    ]
