# Generated by Django 5.0.7 on 2024-08-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0009_alter_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marrigold.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marrigold.order')),
            ],
        ),
    ]
