# Generated by Django 5.0.7 on 2024-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marrigold', '0011_remove_order_items_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='marrigold.menu'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
